sudo: false
language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - "nightly"
  - pypy
  - pypy3
install:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2; fi
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
script: nosetests
after_success:
  - codecov